import 'package:hotel_reservation/modules/category.dart';

import 'modules/hotel.dart';

List<Category> dummyCategories = [
  // Category(id: "c1", title: "Hurghada", imgUrl: 'assets/Hurghada.png'),
  // Category(id: "c2", title: "Sharm El-Shaikh", imgUrl: 'assets/SharmElShiekh.png'),
  // Category(id: "c3", title: "North Coast", imgUrl: 'assets/NorthCoast.png'),
  // Category(id: "c4", title: "Ain Sokhna", imgUrl: 'assets/AinSokhna.png'),
  // Category(id: "c5", title: "Alexandria", imgUrl: 'assets/alex.jpg'),
  // Category(id: "c6", title: "Marsa Matrouh", imgUrl: 'assets/matrouh.jpeg'),
  Category(id: "c1", title: "Hurghada", imgUrl: 'images/hur.png'),
  Category(id: "c2", title: "Sharm El-Shaikh", imgUrl: 'images/sharm.png'),
  Category(id: "c3", title: "North Coast", imgUrl: 'images/north.png'),
  Category(id: "c4", title: "Ain Sokhna", imgUrl: 'images/ain.png'),
  Category(id: "c5", title: "Alexandria", imgUrl: 'images/alex.png'),
  Category(id: "c6", title: "Marsa Matrouh", imgUrl: 'images/matroh.png'),
];

List<Hotel> dummyHotels = [
  Hotel(
      id: "h1",
      title: "Sky View Suites Hotel",
      imgUrl: 'assets/Rectangle 31.png',
      price: '1882 EGP',
      rating: 'Very Good',
      numRating: '1,048 Ratings',
      category: ["c1"],
    star: "4.7"
  ),
  Hotel(
      id: "h2",
      title: "Elaria Hotel Hurgada",
      imgUrl: 'assets/Rectangle 40.png',
      price: '1882 EGP',
      rating: 'Very Good',
      numRating: '1,048 Ratings',
      category: ["c1"], star: '4.1'),
  Hotel(
      id: "h3",
      title: "Coral Sea Aqua Club",
      imgUrl: 'assets/Rectangle 34.png',
      price: '658 EGP',
      rating: 'Excellent',
      numRating: '2,777 Ratings',
      category: ["c2"], star: '2.8'),
  Hotel(
      id: "h4",
      title: "Old Vic Sharm Resort",
      imgUrl: 'assets/Rectangle 42.png',
      price: '899 EGP',
      rating: 'Excellent',
      numRating: '2,777 Ratings',
      category: ["c2"], star: '3.5'),
  Hotel(
      id: "h5",
      title: 'Rixos Alamein',
      imgUrl: 'assets/Rectangle 1.png',
      price: '5570 EGP',
      rating: 'Very Good',
      numRating: '440 Ratings',
      category: ["c3"], star: '3.2'),
  Hotel(
      id: "h6",
      title: 'Al Alamein',
      imgUrl: 'assets/Rectangle 2.png',
      price: '2598 EGP',
      rating: 'Very Good',
      numRating: '440 Ratings',
      category: ["c3"], star: '3.3'),
  Hotel(
      id: "h7",
      title: 'Porto El Jabal Hotel',
      imgUrl: 'assets/3.png',
      price: '4212 EGP',
      rating: 'Very Good',
      numRating: '881 Ratings',
      category: ["c4"], star: '2.6'),
  Hotel(
      id: "h8",
      title: 'Miral Hotel',
      imgUrl: 'assets/4.png',
      price: '11230 EGP',
      rating: 'Very Good',
      numRating: '881 Ratings',
      category: ["c4"], star: '3.6'),
  Hotel(
      id: "h9",
      title: 'Tolip Hotel Alexandria',
      imgUrl: 'assets/5.png',
      price: '2555 EGP',
      rating: 'Excellent',
      numRating: '2,048 Ratings',
      category: ["c5"], star: '2.2'),
  Hotel(
      id: "h10",
      title: 'Romance Alexandria Hotel',
      imgUrl: 'assets/6.png',
      price: '1789 EGP',
      rating: 'Excellent',
      numRating: '2,048 Ratings',
      category: ["c5"], star: '1.9'),
  Hotel(
      id: "h11",
      title: 'Royal Crown Hotel',
      imgUrl: 'assets/7.png',
      price: '4950 EGP',
      rating: 'Very Good',
      numRating: '254 Ratings',
      category: ["c6"], star: '3.3'),
  Hotel(
      id: "h12",
      title: 'Negresco Hotel',
      imgUrl: 'assets/8.png',
      price: '2476 EGP',
      rating: 'Very Good',
      numRating: '254 Ratings',
      category: ["c6"], star: '2.2'),
  Hotel(
      id: "h13",
      title: "Canary Hotel",
      imgUrl: 'images/h1.png',
      price: '449 EGP',
      rating: 'Excellent',
      numRating: '2,777 Ratings',
      category: ["c1"], star: '4.2'),
  Hotel(
      id: "h14",
      title: "Ali Baba Safaga Hotel",
      imgUrl: 'images/h2.png',
      price: '4375 EGP',
      rating: 'Excellent',
      numRating: '2,777 Ratings',
      category: ["c1"], star: '3.8'),
  Hotel(
      id: "h15",
      title: "Queen Sharm Italian Club",
      imgUrl: 'images/h3.png',
      price: '2336 EGP',
      rating: 'Excellent',
      numRating: '2,777 Ratings',
      category: ["c2"], star: '2.4'),
  Hotel(
      id: "h16",
      title: "El Khan Sharm Hotel",
      imgUrl: 'images/h4.png',
      price: '7000 EGP',
      rating: 'Excellent',
      numRating: '2,777 Ratings',
      category: ["c2"], star: '4.1'),
  Hotel(
      id: "h17",
      title: 'Borg El Arab Beach Hotel',
      imgUrl: 'assets/h5.jpeg',
      price: '2862 EGP',
      rating: 'Very Good',
      numRating: '440 Ratings',
      category: ["c3"], star: '3.8'),
  Hotel(
      id: "h18",
      title: 'Retal View Aqua Park',
      imgUrl: 'assets/h6.jpeg',
      price: '1960 EGP',
      rating: 'Very Good',
      numRating: '440 Ratings',
      category: ["c3"], star: '2.9'),
  Hotel(
      id: "h19",
      title: 'La Siesta Hotel Al Sokhna',
      imgUrl: 'assets/h7.png',
      price: '5025 EGP',
      rating: 'Very Good',
      numRating: '440 Ratings',
      category: ["c4"], star: '3.7'),
  Hotel(
      id: "h20",
      title: 'Blumar El Dome Hotel',
      imgUrl: 'assets/h8.jpeg',
      price: '6667 EGP',
      rating: 'Very Good',
      numRating: '440 Ratings',
      category: ["c4"], star: '4.1'),
  Hotel(
      id: "h21",
      title: 'Helnan Royal Hotel',
      imgUrl: 'assets/h9.png',
      price: '1789 EGP',
      rating: 'Excellent',
      numRating: '2,048 Ratings',
      category: ["c5"], star: '1.9'),
  Hotel(
      id: "h22",
      title: 'Plaza Hotel',
      imgUrl: 'assets/h10.png',
      price: '4375 EGP',
      rating: 'Excellent',
      numRating: '2,048 Ratings',
      category: ["c5"], star: '2.3'),
  Hotel(
      id: "h23",
      title: 'Triumph White Sands',
      imgUrl: 'assets/h11.jpeg',
      price: '1702 EGP',
      rating: 'Very Good',
      numRating: '254 Ratings',
      category: ["c6"], star: '1.8'),
  Hotel(
      id: "h24",
      title: 'Porto Matrouh Beach Resort',
      imgUrl: 'assets/h12.jpeg',
      price: '2157 EGP',
      rating: 'Very Good',
      numRating: '254 Ratings',
      category: ["c6"], star: '2.0'),
];
